name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Ruff (Lint Check)
        run: |
          ruff check .

      - name: Run Bandit (Security Scan)
        run: |
          bandit -r app src -ll

      - name: Run Pytest
        run: |
          pytest -v --maxfail=1 --disable-warnings

              - name: Run Pytest with Coverage
        run: |
          pytest --cov=src --cov=app --cov-fail-under=80

